/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreatePostRouteImport } from './routes/createPost'
import { Route as IndexRouteImport } from './routes/index'

const CreatePostRoute = CreatePostRouteImport.update({
  id: '/createPost',
  path: '/createPost',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createPost': typeof CreatePostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createPost': typeof CreatePostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/createPost': typeof CreatePostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createPost'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createPost'
  id: '__root__' | '/' | '/createPost'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatePostRoute: typeof CreatePostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/createPost': {
      id: '/createPost'
      path: '/createPost'
      fullPath: '/createPost'
      preLoaderRoute: typeof CreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatePostRoute: CreatePostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
